# Generated by Django 4.2.13 on 2024-09-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.BigIntegerField()),
                ('lesson_info', models.CharField(max_length=255)),
                ('class_letter', models.CharField(max_length=255)),
                ('group_number', models.IntegerField()),
                ('date', models.DateField()),
                ('info_type', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('class_letter', models.CharField(blank=True, default=None)),
                ('group_number', models.IntegerField(blank=True, default=0)),
                ('u_group_number', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='model_ptr',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
