# Generated by Django 4.2.13 on 2024-09-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_schedule_users_remove_post_model_ptr_delete_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='common_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.BigIntegerField()),
                ('lesson_info', models.CharField(max_length=255)),
                ('class_letter', models.CharField(max_length=255)),
                ('group_number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='uday_schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.BigIntegerField()),
                ('lesson_info', models.CharField(max_length=255)),
                ('group_number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='schedule',
        ),
    ]
