# Generated by Django 4.2.13 on 2024-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_common_schedule_uday_schedule_delete_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='common_schedule',
            name='lesson_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='uday_schedule',
            name='lesson_number',
            field=models.IntegerField(),
        ),
    ]
