# Generated by Django 4.2.13 on 2024-09-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_alter_common_schedule_lesson_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='common_schedule',
            new_name='regular_schedule',
        ),
    ]
