# Generated by Django 4.2.13 on 2024-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_rename_common_schedule_regular_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular_schedule',
            name='lesson_info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uday_schedule',
            name='lesson_info',
            field=models.TextField(),
        ),
    ]
